// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cache/cache.proto

package proto_cache

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Item) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{1}
}

func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (m *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(m, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetRes struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CacheHit             bool     `protobuf:"varint,2,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRes) Reset()         { *m = GetRes{} }
func (m *GetRes) String() string { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()    {}
func (*GetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{2}
}

func (m *GetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRes.Unmarshal(m, b)
}
func (m *GetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRes.Marshal(b, m, deterministic)
}
func (m *GetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRes.Merge(m, src)
}
func (m *GetRes) XXX_Size() int {
	return xxx_messageInfo_GetRes.Size(m)
}
func (m *GetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetRes proto.InternalMessageInfo

func (m *GetRes) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetRes) GetCacheHit() bool {
	if m != nil {
		return m.CacheHit
	}
	return false
}

type SetRes struct {
	Evicted              bool     `protobuf:"varint,1,opt,name=evicted,proto3" json:"evicted,omitempty"`
	EvictedItem          *Item    `protobuf:"bytes,2,opt,name=evicted_item,json=evictedItem,proto3" json:"evicted_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRes) Reset()         { *m = SetRes{} }
func (m *SetRes) String() string { return proto.CompactTextString(m) }
func (*SetRes) ProtoMessage()    {}
func (*SetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{3}
}

func (m *SetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRes.Unmarshal(m, b)
}
func (m *SetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRes.Marshal(b, m, deterministic)
}
func (m *SetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRes.Merge(m, src)
}
func (m *SetRes) XXX_Size() int {
	return xxx_messageInfo_SetRes.Size(m)
}
func (m *SetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRes.DiscardUnknown(m)
}

var xxx_messageInfo_SetRes proto.InternalMessageInfo

func (m *SetRes) GetEvicted() bool {
	if m != nil {
		return m.Evicted
	}
	return false
}

func (m *SetRes) GetEvictedItem() *Item {
	if m != nil {
		return m.EvictedItem
	}
	return nil
}

type KeysRes struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeysRes) Reset()         { *m = KeysRes{} }
func (m *KeysRes) String() string { return proto.CompactTextString(m) }
func (*KeysRes) ProtoMessage()    {}
func (*KeysRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{4}
}

func (m *KeysRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeysRes.Unmarshal(m, b)
}
func (m *KeysRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeysRes.Marshal(b, m, deterministic)
}
func (m *KeysRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysRes.Merge(m, src)
}
func (m *KeysRes) XXX_Size() int {
	return xxx_messageInfo_KeysRes.Size(m)
}
func (m *KeysRes) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysRes.DiscardUnknown(m)
}

var xxx_messageInfo_KeysRes proto.InternalMessageInfo

func (m *KeysRes) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type CapRes struct {
	Cap                  int64    `protobuf:"varint,1,opt,name=cap,proto3" json:"cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapRes) Reset()         { *m = CapRes{} }
func (m *CapRes) String() string { return proto.CompactTextString(m) }
func (*CapRes) ProtoMessage()    {}
func (*CapRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{5}
}

func (m *CapRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapRes.Unmarshal(m, b)
}
func (m *CapRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapRes.Marshal(b, m, deterministic)
}
func (m *CapRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapRes.Merge(m, src)
}
func (m *CapRes) XXX_Size() int {
	return xxx_messageInfo_CapRes.Size(m)
}
func (m *CapRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CapRes.DiscardUnknown(m)
}

var xxx_messageInfo_CapRes proto.InternalMessageInfo

func (m *CapRes) GetCap() int64 {
	if m != nil {
		return m.Cap
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1f9ea1cfcadf4, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Item)(nil), "proto.cache.Item")
	proto.RegisterType((*GetReq)(nil), "proto.cache.GetReq")
	proto.RegisterType((*GetRes)(nil), "proto.cache.GetRes")
	proto.RegisterType((*SetRes)(nil), "proto.cache.SetRes")
	proto.RegisterType((*KeysRes)(nil), "proto.cache.KeysRes")
	proto.RegisterType((*CapRes)(nil), "proto.cache.CapRes")
	proto.RegisterType((*Empty)(nil), "proto.cache.empty")
}

func init() { proto.RegisterFile("proto/cache/cache.proto", fileDescriptor_ecb1f9ea1cfcadf4) }

var fileDescriptor_ecb1f9ea1cfcadf4 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0x80, 0x5b, 0x16, 0x28, 0x0c, 0x1c, 0x70, 0x24, 0xb1, 0xc1, 0x98, 0x90, 0x3d, 0x71, 0x2a,
	0x82, 0x7a, 0xf2, 0x48, 0x22, 0x1a, 0x6f, 0xdb, 0x8b, 0x37, 0x52, 0xeb, 0x24, 0x6d, 0xa0, 0xa1,
	0xd2, 0xa5, 0x49, 0x5f, 0xc2, 0x67, 0x36, 0x3b, 0x2d, 0x91, 0x4a, 0x2f, 0xed, 0xcc, 0xb7, 0xfb,
	0xcd, 0xcf, 0xc2, 0x4d, 0x7a, 0xd8, 0xeb, 0xfd, 0x3c, 0x0c, 0xc2, 0x88, 0xca, 0xaf, 0xc7, 0x04,
	0x07, 0xfc, 0xf3, 0x18, 0x49, 0x0f, 0xda, 0x6f, 0x9a, 0x12, 0x1c, 0x81, 0xd8, 0x52, 0xe1, 0xda,
	0x53, 0x7b, 0xd6, 0x57, 0x26, 0xc4, 0x31, 0x74, 0xf2, 0x60, 0x77, 0x24, 0xb7, 0xc5, 0xac, 0x4c,
	0xe4, 0x04, 0xba, 0x6b, 0xd2, 0x8a, 0xbe, 0x2f, 0x0d, 0xf9, 0x5c, 0x9d, 0x65, 0x7f, 0xae, 0x7d,
	0xe6, 0xe2, 0x2d, 0xf4, 0xb9, 0xe9, 0x26, 0x8a, 0x35, 0x57, 0xed, 0xa9, 0x1e, 0x83, 0xd7, 0x58,
	0xcb, 0x0f, 0xe8, 0xfa, 0xa5, 0xec, 0x82, 0x43, 0x79, 0x1c, 0x6a, 0xfa, 0x62, 0xbd, 0xa7, 0x4e,
	0x29, 0x3e, 0xc2, 0xb0, 0x0a, 0x37, 0xb1, 0xa6, 0x84, 0x6b, 0x0c, 0x96, 0x57, 0xde, 0xd9, 0x42,
	0x9e, 0xd9, 0x46, 0x0d, 0xaa, 0x6b, 0x26, 0x91, 0x77, 0xe0, 0xbc, 0x53, 0x91, 0x99, 0xd2, 0x08,
	0xed, 0x2d, 0x15, 0x99, 0x6b, 0x4f, 0xc5, 0xac, 0xaf, 0x38, 0x36, 0x1b, 0xad, 0x82, 0xd4, 0x9c,
	0x8e, 0x40, 0x84, 0x41, 0xca, 0x4d, 0x85, 0x32, 0xa1, 0x74, 0xa0, 0x43, 0x49, 0xaa, 0x8b, 0xe5,
	0x4f, 0x0b, 0x86, 0x2b, 0x53, 0xdf, 0xa7, 0x43, 0x1e, 0x87, 0x84, 0x0b, 0x10, 0x6b, 0xd2, 0x78,
	0x5d, 0xeb, 0x5d, 0xbe, 0xcc, 0xa4, 0x01, 0x66, 0xd2, 0xc2, 0x39, 0x08, 0x9f, 0x34, 0x5e, 0x8e,
	0xfb, 0x4f, 0xf0, 0x4f, 0xc2, 0x13, 0x38, 0x6b, 0xd2, 0x66, 0x76, 0xc4, 0xda, 0x0d, 0x9e, 0x69,
	0x32, 0xae, 0xb1, 0x6a, 0x45, 0x69, 0xe1, 0x02, 0x3a, 0x2f, 0xbb, 0x63, 0x16, 0x35, 0x4a, 0x0d,
	0x4c, 0x5a, 0x78, 0x0f, 0x62, 0x15, 0xa4, 0x8d, 0x42, 0x7d, 0xb6, 0xf2, 0xa5, 0xa4, 0xf5, 0xd9,
	0x65, 0xfa, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xe5, 0x7f, 0xb5, 0x66, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheServiceClient is the client API for CacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheServiceClient interface {
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error)
	Set(ctx context.Context, in *Item, opts ...grpc.CallOption) (*SetRes, error)
	GetKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysRes, error)
	Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Cap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapRes, error)
}

type cacheServiceClient struct {
	cc *grpc.ClientConn
}

func NewCacheServiceClient(cc *grpc.ClientConn) CacheServiceClient {
	return &cacheServiceClient{cc}
}

func (c *cacheServiceClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetRes, error) {
	out := new(GetRes)
	err := c.cc.Invoke(ctx, "/proto.cache.CacheService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Set(ctx context.Context, in *Item, opts ...grpc.CallOption) (*SetRes, error) {
	out := new(SetRes)
	err := c.cc.Invoke(ctx, "/proto.cache.CacheService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) GetKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KeysRes, error) {
	out := new(KeysRes)
	err := c.cc.Invoke(ctx, "/proto.cache.CacheService/GetKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Flush(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.cache.CacheService/Flush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheServiceClient) Cap(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapRes, error) {
	out := new(CapRes)
	err := c.cc.Invoke(ctx, "/proto.cache.CacheService/Cap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServiceServer is the server API for CacheService service.
type CacheServiceServer interface {
	Get(context.Context, *GetReq) (*GetRes, error)
	Set(context.Context, *Item) (*SetRes, error)
	GetKeys(context.Context, *Empty) (*KeysRes, error)
	Flush(context.Context, *Empty) (*Empty, error)
	Cap(context.Context, *Empty) (*CapRes, error)
}

// UnimplementedCacheServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCacheServiceServer struct {
}

func (*UnimplementedCacheServiceServer) Get(ctx context.Context, req *GetReq) (*GetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCacheServiceServer) Set(ctx context.Context, req *Item) (*SetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedCacheServiceServer) GetKeys(ctx context.Context, req *Empty) (*KeysRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeys not implemented")
}
func (*UnimplementedCacheServiceServer) Flush(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Flush not implemented")
}
func (*UnimplementedCacheServiceServer) Cap(ctx context.Context, req *Empty) (*CapRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cap not implemented")
}

func RegisterCacheServiceServer(s *grpc.Server, srv CacheServiceServer) {
	s.RegisterService(&_CacheService_serviceDesc, srv)
}

func _CacheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cache.CacheService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cache.CacheService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Set(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_GetKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).GetKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cache.CacheService/GetKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).GetKeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cache.CacheService/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Flush(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheService_Cap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServiceServer).Cap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cache.CacheService/Cap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServiceServer).Cap(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _CacheService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.cache.CacheService",
	HandlerType: (*CacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CacheService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _CacheService_Set_Handler,
		},
		{
			MethodName: "GetKeys",
			Handler:    _CacheService_GetKeys_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _CacheService_Flush_Handler,
		},
		{
			MethodName: "Cap",
			Handler:    _CacheService_Cap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cache/cache.proto",
}
