// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: protos/cache-service/cache.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Item) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	CacheHit bool   `protobuf:"varint,2,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
}

func (x *GetRes) Reset() {
	*x = GetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRes) ProtoMessage() {}

func (x *GetRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRes.ProtoReflect.Descriptor instead.
func (*GetRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetRes) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

type SetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Evicted     bool  `protobuf:"varint,1,opt,name=evicted,proto3" json:"evicted,omitempty"`
	EvictedItem *Item `protobuf:"bytes,2,opt,name=evicted_item,json=evictedItem,proto3" json:"evicted_item,omitempty"`
}

func (x *SetRes) Reset() {
	*x = SetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRes) ProtoMessage() {}

func (x *SetRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRes.ProtoReflect.Descriptor instead.
func (*SetRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{4}
}

func (x *SetRes) GetEvicted() bool {
	if x != nil {
		return x.Evicted
	}
	return false
}

func (x *SetRes) GetEvictedItem() *Item {
	if x != nil {
		return x.EvictedItem
	}
	return nil
}

type KeysRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *KeysRes) Reset() {
	*x = KeysRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeysRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRes) ProtoMessage() {}

func (x *KeysRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRes.ProtoReflect.Descriptor instead.
func (*KeysRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{5}
}

func (x *KeysRes) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetFirstOrLastRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetFirstOrLastRes) Reset() {
	*x = GetFirstOrLastRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFirstOrLastRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFirstOrLastRes) ProtoMessage() {}

func (x *GetFirstOrLastRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFirstOrLastRes.ProtoReflect.Descriptor instead.
func (*GetFirstOrLastRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{6}
}

func (x *GetFirstOrLastRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CapRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cap int64 `protobuf:"varint,1,opt,name=cap,proto3" json:"cap,omitempty"`
}

func (x *CapRes) Reset() {
	*x = CapRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CapRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapRes) ProtoMessage() {}

func (x *CapRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapRes.ProtoReflect.Descriptor instead.
func (*CapRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{7}
}

func (x *CapRes) GetCap() int64 {
	if x != nil {
		return x.Cap
	}
	return 0
}

type LenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len int64 `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
}

func (x *LenRes) Reset() {
	*x = LenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_cache_service_cache_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LenRes) ProtoMessage() {}

func (x *LenRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_cache_service_cache_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LenRes.ProtoReflect.Descriptor instead.
func (*LenRes) Descriptor() ([]byte, []int) {
	return file_protos_cache_service_cache_proto_rawDescGZIP(), []int{8}
}

func (x *LenRes) GetLen() int64 {
	if x != nil {
		return x.Len
	}
	return 0
}

var File_protos_cache_service_cache_proto protoreflect.FileDescriptor

var file_protos_cache_service_cache_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x07, 0x0a, 0x05, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f,
	0x68, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x48, 0x69, 0x74, 0x22, 0x5a, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x0c, 0x65, 0x76, 0x69, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0b, 0x65, 0x76, 0x69, 0x63, 0x74, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x22,
	0x1d, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65,
	0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x29,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x72, 0x4c, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x43, 0x61, 0x70,
	0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x63, 0x61, 0x70, 0x22, 0x1a, 0x0a, 0x06, 0x4c, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x65,
	0x6e, 0x32, 0xe3, 0x03, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x35, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x15, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x03, 0x53, 0x65, 0x74,
	0x12, 0x13, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x15, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x16, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x72, 0x73, 0x74, 0x4f, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x20, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x72, 0x4c, 0x61, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x05, 0x46, 0x6c, 0x75, 0x73, 0x68, 0x12, 0x14, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x03, 0x43,
	0x61, 0x70, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x34, 0x0a, 0x03, 0x4c, 0x65, 0x6e, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_cache_service_cache_proto_rawDescOnce sync.Once
	file_protos_cache_service_cache_proto_rawDescData = file_protos_cache_service_cache_proto_rawDesc
)

func file_protos_cache_service_cache_proto_rawDescGZIP() []byte {
	file_protos_cache_service_cache_proto_rawDescOnce.Do(func() {
		file_protos_cache_service_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_cache_service_cache_proto_rawDescData)
	})
	return file_protos_cache_service_cache_proto_rawDescData
}

var file_protos_cache_service_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protos_cache_service_cache_proto_goTypes = []interface{}{
	(*Empty)(nil),             // 0: cache.service.empty
	(*Item)(nil),              // 1: cache.service.Item
	(*GetReq)(nil),            // 2: cache.service.GetReq
	(*GetRes)(nil),            // 3: cache.service.GetRes
	(*SetRes)(nil),            // 4: cache.service.SetRes
	(*KeysRes)(nil),           // 5: cache.service.KeysRes
	(*GetFirstOrLastRes)(nil), // 6: cache.service.GetFirstOrLastRes
	(*CapRes)(nil),            // 7: cache.service.CapRes
	(*LenRes)(nil),            // 8: cache.service.LenRes
}
var file_protos_cache_service_cache_proto_depIdxs = []int32{
	1, // 0: cache.service.SetRes.evicted_item:type_name -> cache.service.Item
	2, // 1: cache.service.CacheService.Get:input_type -> cache.service.GetReq
	1, // 2: cache.service.CacheService.Set:input_type -> cache.service.Item
	0, // 3: cache.service.CacheService.GetKeys:input_type -> cache.service.empty
	0, // 4: cache.service.CacheService.GetFirst:input_type -> cache.service.empty
	0, // 5: cache.service.CacheService.GetLast:input_type -> cache.service.empty
	0, // 6: cache.service.CacheService.Flush:input_type -> cache.service.empty
	0, // 7: cache.service.CacheService.Cap:input_type -> cache.service.empty
	0, // 8: cache.service.CacheService.Len:input_type -> cache.service.empty
	3, // 9: cache.service.CacheService.Get:output_type -> cache.service.GetRes
	4, // 10: cache.service.CacheService.Set:output_type -> cache.service.SetRes
	5, // 11: cache.service.CacheService.GetKeys:output_type -> cache.service.KeysRes
	6, // 12: cache.service.CacheService.GetFirst:output_type -> cache.service.GetFirstOrLastRes
	6, // 13: cache.service.CacheService.GetLast:output_type -> cache.service.GetFirstOrLastRes
	0, // 14: cache.service.CacheService.Flush:output_type -> cache.service.empty
	7, // 15: cache.service.CacheService.Cap:output_type -> cache.service.CapRes
	8, // 16: cache.service.CacheService.Len:output_type -> cache.service.LenRes
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_cache_service_cache_proto_init() }
func file_protos_cache_service_cache_proto_init() {
	if File_protos_cache_service_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_cache_service_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeysRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFirstOrLastRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CapRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_cache_service_cache_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_cache_service_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_cache_service_cache_proto_goTypes,
		DependencyIndexes: file_protos_cache_service_cache_proto_depIdxs,
		MessageInfos:      file_protos_cache_service_cache_proto_msgTypes,
	}.Build()
	File_protos_cache_service_cache_proto = out.File
	file_protos_cache_service_cache_proto_rawDesc = nil
	file_protos_cache_service_cache_proto_goTypes = nil
	file_protos_cache_service_cache_proto_depIdxs = nil
}
